name: Run Gradle Build

on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Upload built mod JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: Zen-1.8.9
          path: build/libs/zen-1.8.9-forge-dev-${{ github.run_number }}.jar

  send-to-discord:
    if: github.event_name == 'push'
    needs: gradle
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Download built artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: Zen-1.8.9
          path: ./artifact

      - name: Send jar to Discord
        run: |
          JAR_FILE=./artifact/zen-1.8.9-forge-dev-${BUILD_NUMBER}.jar
          [ -f "$JAR_FILE" ] || exit 1
          curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "payload_json={\"content\":\"Zen build: zen-1.8.9-forge-dev-${BUILD_NUMBER}.jar\"}" \
            -F "file=@${JAR_FILE}" \
            "$DISCORD_WEBHOOK_URL"