name: Run Gradle Build

on:
  - push
  - pull_request

jobs:
  gradle:
    runs-on: ubuntu-latest
    env:
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4.1.1

      - name: Setup Java
        uses: actions/setup-java@v4.0.0
        with:
          distribution: temurin
          java-version: 17

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4

      - name: Execute Gradle build
        run: ./gradlew build

      - name: Rename built JAR
        run: |
          ORIGINAL_JAR=$(find build/libs -name "*.jar" | head -n 1)
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          
          if [[ "$COMMIT_MESSAGE" == *"Bump version"* ]]; then
            TARGET_JAR="$ORIGINAL_JAR"
          else
            TARGET_JAR="build/libs/zen-1.8.9-forge-dev-${BUILD_NUMBER}.jar"
            mv "$ORIGINAL_JAR" "$TARGET_JAR"
          fi
          
          echo "FINAL_JAR_PATH=$TARGET_JAR" >> $GITHUB_ENV
          echo "JAR_NAME=$(basename $TARGET_JAR)" >> $GITHUB_ENV

      - name: Upload built mod JAR
        uses: actions/upload-artifact@v4.3.0
        with:
          name: ${{ env.JAR_NAME }}
          path: ${{ env.FINAL_JAR_PATH }}

  send-to-discord:
    if: github.event_name == 'push'
    needs: gradle
    runs-on: ubuntu-latest
    env:
      DISCORD_WEBHOOK_URL: ${{ secrets.WEBHOOK }}
      BUILD_NUMBER: ${{ github.run_number }}
    steps:
      - name: Checkout source
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine JAR name
        run: |
          COMMIT_MESSAGE="${{ github.event.head_commit.message }}"
          
          if [[ "$COMMIT_MESSAGE" == *"Bump version"* ]]; then
            echo "JAR_NAME=zen-1.8.9-forge.jar" >> $GITHUB_ENV
          else
            echo "JAR_NAME=zen-1.8.9-forge-dev-${BUILD_NUMBER}.jar" >> $GITHUB_ENV
          fi

      - name: Download built artifact
        uses: actions/download-artifact@v4.1.7
        with:
          name: ${{ env.JAR_NAME }}
          path: ./artifact

      - name: Send jar to Discord
        run: |
          JAR_FILE="./artifact/${{ env.JAR_NAME }}"
          COMMIT_MESSAGE=$(git log -1 --pretty=%s)
          COMMIT_HASH=$(git rev-parse --short HEAD)
          COMMIT_URL="https://github.com/${{ github.repository }}/commit/${COMMIT_HASH}"

          EMBED_PAYLOAD=$(jq -n \
            --arg title "Zen 1.8.9 dev build" \
            --arg desc "[Commit: $COMMIT_MESSAGE]($COMMIT_URL)" \
            '{embeds: [{title: $title, description: $desc, color: 5814783}]}')

          curl -X POST \
            -H "Content-Type: multipart/form-data" \
            -F "payload_json=${EMBED_PAYLOAD}" \
            -F "file=@${JAR_FILE}" \
            "$DISCORD_WEBHOOK_URL"